/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package misClases;

import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JPanel;

/**
 *
 * @author Alondra paulina v
 */
public class ConsultaCostos extends javax.swing.JFrame {
      ConsultaCostos.FondoPanel fondo = new ConsultaCostos.FondoPanel();
    /**
     * Creates new form Consulta6
     */
    public ConsultaCostos() {
        this.setContentPane(fondo);
        initComponents();
        jRadioButtonSencilla.setSelected(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupTiposDeHabitacion = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jRadioButtonSencilla = new javax.swing.JRadioButton();
        jRadioButtonDoble = new javax.swing.JRadioButton();
        jRadioButtonTriple = new javax.swing.JRadioButton();
        jButtonMostrarPrecio = new javax.swing.JButton();
        jLabelMostrarPrecio = new javax.swing.JLabel();
        jButtonLimpiar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(44, 72, 108));
        jLabel1.setText("Seleccione tipo de habitacion:");

        buttonGroupTiposDeHabitacion.add(jRadioButtonSencilla);
        jRadioButtonSencilla.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 18)); // NOI18N
        jRadioButtonSencilla.setForeground(new java.awt.Color(57, 113, 147));
        jRadioButtonSencilla.setText("Habitacion Sencilla");

        buttonGroupTiposDeHabitacion.add(jRadioButtonDoble);
        jRadioButtonDoble.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 18)); // NOI18N
        jRadioButtonDoble.setForeground(new java.awt.Color(57, 113, 147));
        jRadioButtonDoble.setText("Habitacion Doble");

        buttonGroupTiposDeHabitacion.add(jRadioButtonTriple);
        jRadioButtonTriple.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 18)); // NOI18N
        jRadioButtonTriple.setForeground(new java.awt.Color(57, 113, 147));
        jRadioButtonTriple.setText("Habitacion Triple");

        jButtonMostrarPrecio.setBackground(new java.awt.Color(44, 72, 108));
        jButtonMostrarPrecio.setForeground(new java.awt.Color(255, 255, 255));
        jButtonMostrarPrecio.setText("Consultar Precio");
        jButtonMostrarPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMostrarPrecioActionPerformed(evt);
            }
        });

        jLabelMostrarPrecio.setBackground(new java.awt.Color(255, 204, 204));
        jLabelMostrarPrecio.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 24)); // NOI18N
        jLabelMostrarPrecio.setForeground(new java.awt.Color(0, 51, 102));

        jButtonLimpiar.setBackground(new java.awt.Color(44, 72, 108));
        jButtonLimpiar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonLimpiar.setText("Consultar Otra ");
        jButtonLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimpiarActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(0, 102, 102));
        jButton1.setText("Regresar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButtonDoble, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 635, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jRadioButtonSencilla, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jRadioButtonTriple, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelMostrarPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 643, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(149, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jButtonMostrarPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(178, 178, 178)
                        .addComponent(jButtonLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jRadioButtonSencilla)
                .addGap(18, 18, 18)
                .addComponent(jRadioButtonDoble)
                .addGap(18, 18, 18)
                .addComponent(jRadioButtonTriple)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelMostrarPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonMostrarPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimpiarActionPerformed
        // TODO add your handling code here:
        jLabelMostrarPrecio.setText("");
    }//GEN-LAST:event_jButtonLimpiarActionPerformed

    private void jButtonMostrarPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMostrarPrecioActionPerformed
        // TODO add your handling code here:
        String mensaje= "El Precio de esta habitacion es:";
        if (jRadioButtonSencilla.isSelected()){
            mensaje += "$1060";
        }
        if(jRadioButtonDoble.isSelected()){
            mensaje += "$1500";
        }
        if (jRadioButtonTriple.isSelected()){
            mensaje += "$2050";
        }
        jLabelMostrarPrecio.setText(mensaje);
    }//GEN-LAST:event_jButtonMostrarPrecioActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
                MenuSistema Menu = new MenuSistema();
        Menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsultaCostos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsultaCostos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsultaCostos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsultaCostos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConsultaCostos().setVisible(true);
            }
        });
    }
    class FondoPanel extends JPanel{
     private Image imagen;
     
     public void paint (Graphics g){
     imagen = new ImageIcon(getClass().getResource("/misimagenes/fondoConsulta.jpg")).getImage(); 
     g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);
     setOpaque(false);
     super.paint(g);
     }
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupTiposDeHabitacion;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonLimpiar;
    private javax.swing.JButton jButtonMostrarPrecio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelMostrarPrecio;
    private javax.swing.JRadioButton jRadioButtonDoble;
    private javax.swing.JRadioButton jRadioButtonSencilla;
    private javax.swing.JRadioButton jRadioButtonTriple;
    // End of variables declaration//GEN-END:variables
}
