
package misClases;

import com.itextpdf.text.Chunk;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Element;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import controlMySql.MySqlConn;
import java.io.FileOutputStream;
import java.sql.Connection;
//import java.sql.Date;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import com.itextpdf.text.Chunk;
import com.itextpdf.text.Image;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.FontFactory;
import com.itextpdf.text.BaseColor;
import com.itextpdf.text.Font;



public class PDF extends javax.swing.JFrame {

    
    public PDF() {
        initComponents();
        
        //PDF
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));

        jButton1.setBackground(new java.awt.Color(204, 51, 255));
        jButton1.setText("Imprimir Pdf");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(204, 51, 255));
        jButton2.setText("Regresar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(131, 131, 131)
                .addComponent(jButton1)
                .addContainerGap(173, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(31, 31, 31))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(152, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(60, 60, 60)
                .addComponent(jButton2)
                .addGap(33, 33, 33))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Document documento = new Document();
        
        try {
            String ruta = System.getProperty("user.home");
            PdfWriter.getInstance(documento, new FileOutputStream(ruta + "/Escritorio/Reporte.pdf"));
            
            Image header = Image.getInstance("src/misimagenes/firma.jpg");
            header.scaleToFit(100, 100);
            header.setAlignment(Chunk.ALIGN_CENTER);
            Image header2 = Image.getInstance("src/misimagenes/hotelsunset2.png");
            header2.scaleToFit(200, 200);
            header2.setAlignment(Chunk.ALIGN_CENTER);
            
            documento.open();
            PdfPTable tabla = new PdfPTable(10);
            tabla.addCell("NumHab");
            tabla.addCell("Nombre");
            tabla.addCell("Piso");
            tabla.addCell("FechaEntrada");
            tabla.addCell("FechaSalida");
            tabla.addCell("TipoHabitacion");
            tabla.addCell("Personas");
            tabla.addCell("PersonasExtras");
            tabla.addCell("Ciudad");
            tabla.addCell("Dias");
            
            
            try {
                Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/hotel", "root", "");
                PreparedStatement pst = cn.prepareStatement("select * from huespedes");
                
                Paragraph titulo = new Paragraph("Hotel Sunset Akumal");
                titulo.setAlignment(1);
                Paragraph lema = new Paragraph("Somos un hotel 4 estrellas dispuesto a brindale la mejor experiencia, "
                        + "situado sobre una playa de arena blanca, el hotel sunset akumal es el "
                        + "lugar ideal para vivir unas vacaciones inolvidables");
                lema.setAlignment(Element.ALIGN_JUSTIFIED);
                ResultSet rs = pst.executeQuery();
                Paragraph firma = new Paragraph("Nombre y firma del gerente ");
                firma.setAlignment(1);
                Paragraph firma2 = new Paragraph("Alondra de Jesús Firova Ratero");
                firma2.setAlignment(1);
                Date date = new Date();
                DateFormat dateformat = new SimpleDateFormat("dd/MM/yyyy");
                
                
                
                documento.add(header2);
                documento.add(Chunk.NEWLINE);
                documento.add(Chunk.NEWLINE);
                documento.add(titulo);
                documento.add(Chunk.NEWLINE);
                documento.add(lema);
                documento.add(Chunk.NEWLINE);
                documento.add(new Paragraph("Ubicacion: Carretera Fed Chetumal-Puerto Juárez KM 252, 77780 Akumal, Q.R"));
                documento.add(Chunk.NEWLINE);
                documento.add(new Paragraph("Fecha: " + dateformat.format(date)));
                documento.add(Chunk.NEWLINE);
                if (rs.next()){
                    documento.add(new Paragraph("Nombre del huesped: " + rs.getString(2)));
                    documento.add(new Paragraph("Ciudad de origen: " + rs.getString(9)));
                    documento.add(new Paragraph("Fecha de ingreso: " + rs.getString(4)));
                    documento.add(new Paragraph("Fecha de salida: " + rs.getString(5)));
                    documento.add(new Paragraph("Tipo de habitacion: " + rs.getString(6)));
                }
                
                documento.add(new Paragraph("Costo de habitacion: " ));
                documento.add(new Paragraph("Dias en el hotel: " + rs.getString(10)));
                documento.add(new Paragraph("Total a pagar sin cargos extras: " ));
                documento.add(new Paragraph("Total a pagar con cargos extras: " ));
                documento.add(new Paragraph("Lista de cargos extras: " ));
                documento.add(Chunk.NEWLINE);
                documento.add(new Paragraph(firma));
                documento.add(Chunk.NEWLINE);
                documento.add(new Paragraph(firma2));
                documento.add(header);
                documento.add(Chunk.NEWLINE);
                documento.add(new Paragraph("Ya no vengan ¬¬ !!! "));
                documento.add(Chunk.NEWLINE);
                documento.add(Chunk.NEWLINE);
                documento.add(new Paragraph("Salida completada "));
                        
                /*if (rs.next()) {
                    do {                        
                        tabla.addCell(rs.getString(1));
                        tabla.addCell(rs.getString(2));
                        tabla.addCell(rs.getString(3));
                        tabla.addCell(rs.getString(4));
                        tabla.addCell(rs.getString(5));
                        tabla.addCell(rs.getString(6));
                        tabla.addCell(rs.getString(7));
                    } while (rs.next());
                    documento.add(tabla);
                }*/
            } catch (Exception e) {
            }
            documento.close();
            JOptionPane.showMessageDialog(null, "Reporte creado...");
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
                MenuSistema Menu = new MenuSistema();
        Menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PDF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PDF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PDF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PDF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PDF().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
