/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package misClases;

import controlMySql.MySqlConn;
import java.awt.Color;
import javax.swing.JOptionPane;
import misClases.Hotel;
import test.test;
/**
 *
 * @author Alondra paulina v
 */
public class PisosHotel extends javax.swing.JFrame {
    MySqlConn objConn=new MySqlConn();
    
    public static String numHab="";
    /**
     * Creates new form PisosHotel
     */
    public PisosHotel() {

        initComponents();
        EstaOcupada();
        
    }
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelPisoUno = new javax.swing.JPanel();
        jButtonHab102 = new javax.swing.JButton();
        jButtonHab101 = new javax.swing.JButton();
        jButtonHab100 = new javax.swing.JButton();
        jButtonHab105 = new javax.swing.JButton();
        jButtonHab104 = new javax.swing.JButton();
        jButtonHab103 = new javax.swing.JButton();
        jButtonHab108 = new javax.swing.JButton();
        jButtonHab107 = new javax.swing.JButton();
        jButtonHab106 = new javax.swing.JButton();
        jButtonHab111 = new javax.swing.JButton();
        jButtonHab110 = new javax.swing.JButton();
        jButtonHab109 = new javax.swing.JButton();
        jButtonHab114 = new javax.swing.JButton();
        jButtonHab113 = new javax.swing.JButton();
        jButtonHab112 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jPanelPiso2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButtonHab115 = new javax.swing.JButton();
        jButtonHab116 = new javax.swing.JButton();
        jButtonHab117 = new javax.swing.JButton();
        jButtonHab118 = new javax.swing.JButton();
        jButtonHab119 = new javax.swing.JButton();
        jButtonHab120 = new javax.swing.JButton();
        jButtonHab121 = new javax.swing.JButton();
        jButtonHab122 = new javax.swing.JButton();
        jButtonHab123 = new javax.swing.JButton();
        jButtonHab124 = new javax.swing.JButton();
        jButtonHab125 = new javax.swing.JButton();
        jButtonHab126 = new javax.swing.JButton();
        jButtonHab127 = new javax.swing.JButton();
        jButtonHab128 = new javax.swing.JButton();
        jButtonHab129 = new javax.swing.JButton();
        jButton37 = new javax.swing.JButton();
        jButton38 = new javax.swing.JButton();
        jButton39 = new javax.swing.JButton();
        jButtonContinuar = new javax.swing.JButton();
        NumHab = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelPisoUno.setBackground(new java.awt.Color(255, 255, 255));

        jButtonHab102.setBackground(new java.awt.Color(213, 131, 44));
        jButtonHab102.setText("102");
        jButtonHab102.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHab102ActionPerformed(evt);
            }
        });

        jButtonHab101.setBackground(new java.awt.Color(213, 131, 44));
        jButtonHab101.setText("101");
        jButtonHab101.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHab101ActionPerformed(evt);
            }
        });

        jButtonHab100.setBackground(new java.awt.Color(213, 131, 44));
        jButtonHab100.setText("100");
        jButtonHab100.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHab100ActionPerformed(evt);
            }
        });

        jButtonHab105.setBackground(new java.awt.Color(245, 230, 104));
        jButtonHab105.setText("105");
        jButtonHab105.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHab105ActionPerformed(evt);
            }
        });

        jButtonHab104.setBackground(new java.awt.Color(213, 131, 44));
        jButtonHab104.setText("104");
        jButtonHab104.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHab104ActionPerformed(evt);
            }
        });

        jButtonHab103.setBackground(new java.awt.Color(213, 131, 44));
        jButtonHab103.setText("103");
        jButtonHab103.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHab103ActionPerformed(evt);
            }
        });

        jButtonHab108.setBackground(new java.awt.Color(245, 230, 104));
        jButtonHab108.setText("108");
        jButtonHab108.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHab108ActionPerformed(evt);
            }
        });

        jButtonHab107.setBackground(new java.awt.Color(245, 230, 104));
        jButtonHab107.setText("107");
        jButtonHab107.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHab107ActionPerformed(evt);
            }
        });

        jButtonHab106.setBackground(new java.awt.Color(245, 230, 104));
        jButtonHab106.setText("106");
        jButtonHab106.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHab106ActionPerformed(evt);
            }
        });

        jButtonHab111.setBackground(new java.awt.Color(243, 181, 108));
        jButtonHab111.setText("111");
        jButtonHab111.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHab111ActionPerformed(evt);
            }
        });

        jButtonHab110.setBackground(new java.awt.Color(243, 181, 108));
        jButtonHab110.setText("110");
        jButtonHab110.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHab110ActionPerformed(evt);
            }
        });

        jButtonHab109.setBackground(new java.awt.Color(245, 230, 104));
        jButtonHab109.setText("109");
        jButtonHab109.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHab109ActionPerformed(evt);
            }
        });

        jButtonHab114.setBackground(new java.awt.Color(213, 131, 44));
        jButtonHab114.setText("114");
        jButtonHab114.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHab114ActionPerformed(evt);
            }
        });

        jButtonHab113.setBackground(new java.awt.Color(213, 131, 44));
        jButtonHab113.setText("113");
        jButtonHab113.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHab113ActionPerformed(evt);
            }
        });

        jButtonHab112.setBackground(new java.awt.Color(243, 181, 108));
        jButtonHab112.setText("112");
        jButtonHab112.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHab112ActionPerformed(evt);
            }
        });

        jButton16.setText("Alberca con vista al mar");

        jButton17.setText("Bar/Comedor");

        jButton18.setText("Cancha tennis");

        jButton19.setBackground(new java.awt.Color(213, 131, 44));
        jButton19.setText("Habitacion Sencilla");

        jButton20.setBackground(new java.awt.Color(245, 230, 104));
        jButton20.setText("Habitacion Doble");

        jButton21.setBackground(new java.awt.Color(243, 181, 108));
        jButton21.setText("Habitacion Triple");

        javax.swing.GroupLayout jPanelPisoUnoLayout = new javax.swing.GroupLayout(jPanelPisoUno);
        jPanelPisoUno.setLayout(jPanelPisoUnoLayout);
        jPanelPisoUnoLayout.setHorizontalGroup(
            jPanelPisoUnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPisoUnoLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanelPisoUnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanelPisoUnoLayout.createSequentialGroup()
                        .addGroup(jPanelPisoUnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelPisoUnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jButton16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanelPisoUnoLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jButton19)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                        .addGroup(jPanelPisoUnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanelPisoUnoLayout.createSequentialGroup()
                                .addComponent(jButton20, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton21, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(9, 9, 9))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPisoUnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanelPisoUnoLayout.createSequentialGroup()
                                    .addComponent(jButtonHab106, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jButtonHab107, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jButtonHab108, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanelPisoUnoLayout.createSequentialGroup()
                                    .addComponent(jButtonHab103, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jButtonHab104, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jButtonHab105, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelPisoUnoLayout.createSequentialGroup()
                                    .addComponent(jButtonHab109, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jButtonHab110, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jButtonHab111, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanelPisoUnoLayout.createSequentialGroup()
                                    .addComponent(jButtonHab100, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jButtonHab101, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jButtonHab102, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPisoUnoLayout.createSequentialGroup()
                                .addComponent(jButtonHab112, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonHab113, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButtonHab114, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(36, 36, 36))))
        );
        jPanelPisoUnoLayout.setVerticalGroup(
            jPanelPisoUnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPisoUnoLayout.createSequentialGroup()
                .addGroup(jPanelPisoUnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelPisoUnoLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanelPisoUnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton19)
                            .addComponent(jButton21)
                            .addComponent(jButton20))
                        .addGap(58, 58, 58)
                        .addGroup(jPanelPisoUnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonHab102, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonHab101, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonHab100, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelPisoUnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonHab105, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonHab104, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonHab103, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                        .addGroup(jPanelPisoUnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonHab108, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
                            .addComponent(jButtonHab106, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
                            .addComponent(jButtonHab107, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)))
                    .addGroup(jPanelPisoUnoLayout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(jButton16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(jPanelPisoUnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelPisoUnoLayout.createSequentialGroup()
                        .addGroup(jPanelPisoUnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonHab109, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonHab110, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonHab111, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelPisoUnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonHab114, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonHab113, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonHab112, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jButton17, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton18, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        jPanelPiso2.setBackground(new java.awt.Color(255, 255, 255));
        jPanelPiso2.setPreferredSize(new java.awt.Dimension(578, 569));

        jLabel2.setText("Piso 2");

        jButtonHab115.setBackground(new java.awt.Color(245, 230, 104));
        jButtonHab115.setText("115");
        jButtonHab115.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHab115ActionPerformed(evt);
            }
        });

        jButtonHab116.setBackground(new java.awt.Color(245, 230, 104));
        jButtonHab116.setText("116");
        jButtonHab116.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHab116ActionPerformed(evt);
            }
        });

        jButtonHab117.setBackground(new java.awt.Color(245, 230, 104));
        jButtonHab117.setText("117");
        jButtonHab117.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHab117ActionPerformed(evt);
            }
        });

        jButtonHab118.setBackground(new java.awt.Color(245, 230, 104));
        jButtonHab118.setText("118");
        jButtonHab118.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHab118ActionPerformed(evt);
            }
        });

        jButtonHab119.setBackground(new java.awt.Color(245, 230, 104));
        jButtonHab119.setText("119");
        jButtonHab119.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHab119ActionPerformed(evt);
            }
        });

        jButtonHab120.setBackground(new java.awt.Color(245, 230, 104));
        jButtonHab120.setText("120");
        jButtonHab120.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHab120ActionPerformed(evt);
            }
        });

        jButtonHab121.setBackground(new java.awt.Color(243, 181, 108));
        jButtonHab121.setText("121");
        jButtonHab121.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHab121ActionPerformed(evt);
            }
        });

        jButtonHab122.setBackground(new java.awt.Color(243, 181, 108));
        jButtonHab122.setText("122");
        jButtonHab122.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHab122ActionPerformed(evt);
            }
        });

        jButtonHab123.setBackground(new java.awt.Color(243, 181, 108));
        jButtonHab123.setText("123");
        jButtonHab123.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHab123ActionPerformed(evt);
            }
        });

        jButtonHab124.setBackground(new java.awt.Color(243, 181, 108));
        jButtonHab124.setText("124");
        jButtonHab124.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHab124ActionPerformed(evt);
            }
        });

        jButtonHab125.setBackground(new java.awt.Color(243, 181, 108));
        jButtonHab125.setText("125");
        jButtonHab125.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHab125ActionPerformed(evt);
            }
        });

        jButtonHab126.setBackground(new java.awt.Color(243, 181, 108));
        jButtonHab126.setText("126");
        jButtonHab126.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHab126ActionPerformed(evt);
            }
        });

        jButtonHab127.setBackground(new java.awt.Color(245, 230, 104));
        jButtonHab127.setText("127");
        jButtonHab127.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHab127ActionPerformed(evt);
            }
        });

        jButtonHab128.setBackground(new java.awt.Color(213, 131, 44));
        jButtonHab128.setText("128");
        jButtonHab128.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHab128ActionPerformed(evt);
            }
        });

        jButtonHab129.setBackground(new java.awt.Color(213, 131, 44));
        jButtonHab129.setText("129");
        jButtonHab129.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHab129ActionPerformed(evt);
            }
        });

        jButton37.setText("Guarderia");

        jButton38.setText("Spa");

        jButton39.setText("Area de video Juegos");

        jButtonContinuar.setBackground(new java.awt.Color(51, 51, 51));
        jButtonContinuar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonContinuar.setText("Continuar");
        jButtonContinuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonContinuarActionPerformed(evt);
            }
        });

        jLabel1.setText("Numero de la habitacion:");

        javax.swing.GroupLayout jPanelPiso2Layout = new javax.swing.GroupLayout(jPanelPiso2);
        jPanelPiso2.setLayout(jPanelPiso2Layout);
        jPanelPiso2Layout.setHorizontalGroup(
            jPanelPiso2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPiso2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanelPiso2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelPiso2Layout.createSequentialGroup()
                        .addGroup(jPanelPiso2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelPiso2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jButtonHab118, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButtonHab121, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButtonHab115, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelPiso2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelPiso2Layout.createSequentialGroup()
                                .addGroup(jPanelPiso2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButtonHab119, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButtonHab122, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButtonHab116, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanelPiso2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanelPiso2Layout.createSequentialGroup()
                                        .addGroup(jPanelPiso2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jButtonHab117, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jButtonHab123, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jButtonHab120, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(jPanelPiso2Layout.createSequentialGroup()
                                        .addGap(122, 122, 122)
                                        .addComponent(jButton39, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE))))
                            .addComponent(jButton37, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanelPiso2Layout.createSequentialGroup()
                        .addGroup(jPanelPiso2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelPiso2Layout.createSequentialGroup()
                                .addComponent(jButtonHab124, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonHab125, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonHab126, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelPiso2Layout.createSequentialGroup()
                                .addGap(92, 92, 92)
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(NumHab, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelPiso2Layout.createSequentialGroup()
                                .addComponent(jButtonHab127, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonHab128, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonHab129, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(27, 27, 27)
                        .addGroup(jPanelPiso2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelPiso2Layout.createSequentialGroup()
                                .addComponent(jButtonContinuar)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jButton38, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanelPiso2Layout.setVerticalGroup(
            jPanelPiso2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPiso2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanelPiso2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelPiso2Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jButton37, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanelPiso2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonHab115, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonHab116, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonHab117, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanelPiso2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanelPiso2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanelPiso2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonHab118, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonHab119, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonHab120, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelPiso2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonHab121, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonHab122, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonHab123, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanelPiso2Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jButton39, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(jPanelPiso2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelPiso2Layout.createSequentialGroup()
                        .addGroup(jPanelPiso2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonHab124, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonHab125, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonHab126, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelPiso2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonHab127, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanelPiso2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jButtonHab128, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButtonHab129, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jButton38, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanelPiso2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonContinuar)
                    .addComponent(NumHab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelPisoUno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                .addComponent(jPanelPiso2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelPisoUno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanelPiso2, javax.swing.GroupLayout.DEFAULT_SIZE, 575, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonHab121ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHab121ActionPerformed
if("Ocupado".equals(jButtonHab121.getText())){
           JOptionPane.showMessageDialog(null,"habitacion no disponible");
        }else{
           jButtonHab121.setBackground(Color.BLACK);
           jButtonHab121.setForeground(Color.white);
           jButtonHab121.setText("Ocupado");  
           PisosHotel.numHab="121";
           PisosHotel.NumHab.setText("121");
        }         // TODO add your handling code here:
        
    }//GEN-LAST:event_jButtonHab121ActionPerformed
    public void EstaOcupada(){
        Habitacion[] aux;
        aux = new Habitacion[30];
       // aux= new Habitacion[30];

        int op=0 ;
          //pruebas de ocupacion
          jButtonHab100.setBackground(Color.BLACK);
          jButtonHab100.setText("Ocupado");
          jButtonHab100.setForeground(Color.white);
          //for(int i=0;.size>=i;i++){
        
          //}
        switch(op){
            case 1:
                jButtonHab100.setBackground(Color.BLACK);
                jButtonHab100.setText("Ocupado"); 
                jButtonHab100.setForeground(Color.white);
                break;
            case 2:
                
                break;
            case 3:
                
                break;
            case 4:
                
                break;
             
                
        }
    }

    public String getNumHab() {
        return numHab;
    }

    public void setNumHab(String numHab) {
        this.numHab = numHab;
    }
    
    public void llenar(){
    
        }
    
    private void jButtonHab100ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHab100ActionPerformed
       // TODO add your handling code here:
        if("Ocupado".equals(jButtonHab100.getText())){
           JOptionPane.showMessageDialog(null,"habitacion no disponible");
        }else{
           jButtonHab100.setBackground(Color.BLACK);
           jButtonHab100.setForeground(Color.white);
           jButtonHab100.setText("Ocupado");  
           PisosHotel.numHab="100";
           PisosHotel.NumHab.setText("100");
        }
    }//GEN-LAST:event_jButtonHab100ActionPerformed

    private void jButtonContinuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonContinuarActionPerformed
        // TODO add your handling code here:
        numHab=NumHab.getText();
        test a =new test();
        a.chek();  
        this.setVisible(false);     
    }//GEN-LAST:event_jButtonContinuarActionPerformed

    private void jButtonHab101ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHab101ActionPerformed
        // TODO add your handling code here:
       if("Ocupado".equals(jButtonHab101.getText())){
           JOptionPane.showMessageDialog(null,"habitacion no disponible");
        }else{
           jButtonHab101.setBackground(Color.BLACK);
           jButtonHab101.setForeground(Color.white);
           jButtonHab101.setText("Ocupado");  
           PisosHotel.numHab="101";
           PisosHotel.NumHab.setText("101");
        }
    }//GEN-LAST:event_jButtonHab101ActionPerformed

    private void jButtonHab102ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHab102ActionPerformed
        // TODO add your handling code here:
        if("Ocupado".equals(jButtonHab102.getText())){
           JOptionPane.showMessageDialog(null,"habitacion no disponible");
        }else{
           jButtonHab102.setBackground(Color.BLACK);
           jButtonHab102.setForeground(Color.white);
           jButtonHab102.setText("Ocupado");  
           PisosHotel.numHab="102";
           PisosHotel.NumHab.setText("102");
        }
    }//GEN-LAST:event_jButtonHab102ActionPerformed

    private void jButtonHab103ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHab103ActionPerformed
        // TODO add your handling code here:
        if("Ocupado".equals(jButtonHab103.getText())){
           JOptionPane.showMessageDialog(null,"habitacion no disponible");
        }else{
           jButtonHab103.setBackground(Color.BLACK);
           jButtonHab103.setForeground(Color.white);
           jButtonHab103.setText("Ocupado");  
           PisosHotel.numHab="103";
           PisosHotel.NumHab.setText("103");
        }
    }//GEN-LAST:event_jButtonHab103ActionPerformed

    private void jButtonHab104ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHab104ActionPerformed
        if("Ocupado".equals(jButtonHab104.getText())){
           JOptionPane.showMessageDialog(null,"habitacion no disponible");
        }else{
           jButtonHab104.setBackground(Color.BLACK);
           jButtonHab104.setForeground(Color.white);
           jButtonHab104.setText("Ocupado");  
           PisosHotel.numHab="104";
           PisosHotel.NumHab.setText("104");
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonHab104ActionPerformed

    private void jButtonHab105ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHab105ActionPerformed
        // TODO add your handling code here:
                if("Ocupado".equals(jButtonHab105.getText())){
           JOptionPane.showMessageDialog(null,"habitacion no disponible");
        }else{
           jButtonHab105.setBackground(Color.BLACK);
           jButtonHab105.setForeground(Color.white);
           jButtonHab105.setText("Ocupado");  
           PisosHotel.numHab="105";
           PisosHotel.NumHab.setText("105");
        }
    }//GEN-LAST:event_jButtonHab105ActionPerformed

    private void jButtonHab106ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHab106ActionPerformed
        // TODO add your handling code here:
                if("Ocupado".equals(jButtonHab106.getText())){
           JOptionPane.showMessageDialog(null,"habitacion no disponible");
        }else{
           jButtonHab106.setBackground(Color.BLACK);
           jButtonHab106.setForeground(Color.white);
           jButtonHab106.setText("Ocupado");  
           PisosHotel.numHab="106";
           PisosHotel.NumHab.setText("106");
        }
    }//GEN-LAST:event_jButtonHab106ActionPerformed

    private void jButtonHab107ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHab107ActionPerformed
        if("Ocupado".equals(jButtonHab107.getText())){
           JOptionPane.showMessageDialog(null,"habitacion no disponible");
        }else{
           jButtonHab107.setBackground(Color.BLACK);
           jButtonHab107.setForeground(Color.white);
           jButtonHab107.setText("Ocupado");  
           PisosHotel.numHab="107";
           PisosHotel.NumHab.setText("107");
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonHab107ActionPerformed

    private void jButtonHab108ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHab108ActionPerformed
        if("Ocupado".equals(jButtonHab108.getText())){
           JOptionPane.showMessageDialog(null,"habitacion no disponible");
        }else{
           jButtonHab108.setBackground(Color.BLACK);
           jButtonHab108.setForeground(Color.white);
           jButtonHab108.setText("Ocupado");  
           PisosHotel.numHab="108";
           PisosHotel.NumHab.setText("108");
        }      
    }//GEN-LAST:event_jButtonHab108ActionPerformed

    private void jButtonHab109ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHab109ActionPerformed
        if("Ocupado".equals(jButtonHab109.getText())){
           JOptionPane.showMessageDialog(null,"habitacion no disponible");
        }else{
           jButtonHab109.setBackground(Color.BLACK);
           jButtonHab109.setForeground(Color.white);
           jButtonHab109.setText("Ocupado");  
           PisosHotel.numHab="109";
           PisosHotel.NumHab.setText("109");
        }        
    }//GEN-LAST:event_jButtonHab109ActionPerformed

    private void jButtonHab110ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHab110ActionPerformed
        // TODO add your handling code here:
    if("Ocupado".equals(jButtonHab110.getText())){
           JOptionPane.showMessageDialog(null,"habitacion no disponible");
        }else{
           jButtonHab110.setBackground(Color.BLACK);
           jButtonHab110.setForeground(Color.white);
           jButtonHab110.setText("Ocupado");  
           PisosHotel.numHab="110";
           PisosHotel.NumHab.setText("110");
        }  
    }//GEN-LAST:event_jButtonHab110ActionPerformed

    private void jButtonHab111ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHab111ActionPerformed
        // TODO add your handling code here:
        if("Ocupado".equals(jButtonHab111.getText())){
           JOptionPane.showMessageDialog(null,"habitacion no disponible");
        }else{
           jButtonHab111.setBackground(Color.BLACK);
           jButtonHab111.setForeground(Color.white);
           jButtonHab111.setText("Ocupado");  
           PisosHotel.numHab="111";
           PisosHotel.NumHab.setText("111");
        } 
    }//GEN-LAST:event_jButtonHab111ActionPerformed

    private void jButtonHab112ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHab112ActionPerformed

        if("Ocupado".equals(jButtonHab112.getText())){
           JOptionPane.showMessageDialog(null,"habitacion no disponible");
        }else{
           jButtonHab112.setBackground(Color.BLACK);
           jButtonHab112.setForeground(Color.white);
           jButtonHab112.setText("Ocupado");  
           PisosHotel.numHab="112";
           PisosHotel.NumHab.setText("112");
        } // TODO add your handling code here:
    }//GEN-LAST:event_jButtonHab112ActionPerformed

    private void jButtonHab113ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHab113ActionPerformed
if("Ocupado".equals(jButtonHab113.getText())){
           JOptionPane.showMessageDialog(null,"habitacion no disponible");
        }else{
           jButtonHab113.setBackground(Color.BLACK);
           jButtonHab113.setForeground(Color.white);
           jButtonHab113.setText("Ocupado");  
           PisosHotel.numHab="113";
           PisosHotel.NumHab.setText("113");
        }         // TODO add your handling code here:
    }//GEN-LAST:event_jButtonHab113ActionPerformed

    private void jButtonHab114ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHab114ActionPerformed
if("Ocupado".equals(jButtonHab114.getText())){
           JOptionPane.showMessageDialog(null,"habitacion no disponible");
        }else{
           jButtonHab114.setBackground(Color.BLACK);
           jButtonHab114.setForeground(Color.white);
           jButtonHab114.setText("Ocupado");  
           PisosHotel.numHab="114";
           PisosHotel.NumHab.setText("114");
        }         // TODO add your handling code here:
    }//GEN-LAST:event_jButtonHab114ActionPerformed

    private void jButtonHab115ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHab115ActionPerformed
if("Ocupado".equals(jButtonHab115.getText())){
           JOptionPane.showMessageDialog(null,"habitacion no disponible");
        }else{
           jButtonHab115.setBackground(Color.BLACK);
           jButtonHab115.setForeground(Color.white);
           jButtonHab115.setText("Ocupado");  
           PisosHotel.numHab="115";
           PisosHotel.NumHab.setText("115");
        }         // TODO add your handling code here:
    }//GEN-LAST:event_jButtonHab115ActionPerformed

    private void jButtonHab116ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHab116ActionPerformed
if("Ocupado".equals(jButtonHab116.getText())){
           JOptionPane.showMessageDialog(null,"habitacion no disponible");
        }else{
           jButtonHab116.setBackground(Color.BLACK);
           jButtonHab116.setForeground(Color.white);
           jButtonHab116.setText("Ocupado");  
           PisosHotel.numHab="116";
           PisosHotel.NumHab.setText("116");
        }         // TODO add your handling code here:
    }//GEN-LAST:event_jButtonHab116ActionPerformed

    private void jButtonHab117ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHab117ActionPerformed
if("Ocupado".equals(jButtonHab117.getText())){
           JOptionPane.showMessageDialog(null,"habitacion no disponible");
        }else{
           jButtonHab117.setBackground(Color.BLACK);
           jButtonHab117.setForeground(Color.white);
           jButtonHab117.setText("Ocupado");  
           PisosHotel.numHab="117";
           PisosHotel.NumHab.setText("117");
        }         // TODO add your handling code here:
    }//GEN-LAST:event_jButtonHab117ActionPerformed

    private void jButtonHab118ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHab118ActionPerformed
if("Ocupado".equals(jButtonHab118.getText())){
           JOptionPane.showMessageDialog(null,"habitacion no disponible");
        }else{
           jButtonHab118.setBackground(Color.BLACK);
           jButtonHab118.setForeground(Color.white);
           jButtonHab118.setText("Ocupado");  
           PisosHotel.numHab="118";
           PisosHotel.NumHab.setText("118");
        }         // TODO add your handling code here:
    }//GEN-LAST:event_jButtonHab118ActionPerformed

    private void jButtonHab119ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHab119ActionPerformed
if("Ocupado".equals(jButtonHab119.getText())){
           JOptionPane.showMessageDialog(null,"habitacion no disponible");
        }else{
           jButtonHab119.setBackground(Color.BLACK);
           jButtonHab119.setForeground(Color.white);
           jButtonHab119.setText("Ocupado");  
           PisosHotel.numHab="119";
           PisosHotel.NumHab.setText("119");
        }         // TODO add your handling code here:
    }//GEN-LAST:event_jButtonHab119ActionPerformed

    private void jButtonHab120ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHab120ActionPerformed
if("Ocupado".equals(jButtonHab120.getText())){
           JOptionPane.showMessageDialog(null,"habitacion no disponible");
        }else{
           jButtonHab120.setBackground(Color.BLACK);
           jButtonHab120.setForeground(Color.white);
           jButtonHab120.setText("Ocupado");  
           PisosHotel.numHab="120";
           PisosHotel.NumHab.setText("120");
        }         // TODO add your handling code here:
    }//GEN-LAST:event_jButtonHab120ActionPerformed

    private void jButtonHab122ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHab122ActionPerformed
        // TODO add your handling code here:
        if("Ocupado".equals(jButtonHab122.getText())){
           JOptionPane.showMessageDialog(null,"habitacion no disponible");
        }else{
           jButtonHab122.setBackground(Color.BLACK);
           jButtonHab122.setForeground(Color.white);
           jButtonHab122.setText("Ocupado");  
           PisosHotel.numHab="122";
           PisosHotel.NumHab.setText("122");
        }   
    }//GEN-LAST:event_jButtonHab122ActionPerformed

    private void jButtonHab123ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHab123ActionPerformed
if("Ocupado".equals(jButtonHab123.getText())){
           JOptionPane.showMessageDialog(null,"habitacion no disponible");
        }else{
           jButtonHab123.setBackground(Color.BLACK);
           jButtonHab123.setForeground(Color.white);
           jButtonHab123.setText("Ocupado");  
           PisosHotel.numHab="123";
           PisosHotel.NumHab.setText("123");
        }           // TODO add your handling code here:
    }//GEN-LAST:event_jButtonHab123ActionPerformed

    private void jButtonHab124ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHab124ActionPerformed
if("Ocupado".equals(jButtonHab124.getText())){
           JOptionPane.showMessageDialog(null,"habitacion no disponible");
        }else{
           jButtonHab124.setBackground(Color.BLACK);
           jButtonHab124.setForeground(Color.white);
           jButtonHab124.setText("Ocupado");  
           PisosHotel.numHab="124";
           PisosHotel.NumHab.setText("124");
        }           // TODO add your handling code here:
    }//GEN-LAST:event_jButtonHab124ActionPerformed

    private void jButtonHab125ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHab125ActionPerformed
if("Ocupado".equals(jButtonHab125.getText())){
           JOptionPane.showMessageDialog(null,"habitacion no disponible");
        }else{
           jButtonHab125.setBackground(Color.BLACK);
           jButtonHab125.setForeground(Color.white);
           jButtonHab125.setText("Ocupado");  
           PisosHotel.numHab="125";
           PisosHotel.NumHab.setText("125");
        }           // TODO add your handling code here:
    }//GEN-LAST:event_jButtonHab125ActionPerformed

    private void jButtonHab126ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHab126ActionPerformed
if("Ocupado".equals(jButtonHab126.getText())){
           JOptionPane.showMessageDialog(null,"habitacion no disponible");
        }else{
           jButtonHab126.setBackground(Color.BLACK);
           jButtonHab126.setForeground(Color.white);
           jButtonHab126.setText("Ocupado");  
           PisosHotel.numHab="126";
           PisosHotel.NumHab.setText("126");
        }           // TODO add your handling code here:
    }//GEN-LAST:event_jButtonHab126ActionPerformed

    private void jButtonHab127ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHab127ActionPerformed
if("Ocupado".equals(jButtonHab127.getText())){
           JOptionPane.showMessageDialog(null,"habitacion no disponible");
        }else{
           jButtonHab127.setBackground(Color.BLACK);
           jButtonHab127.setForeground(Color.white);
           jButtonHab127.setText("Ocupado");  
           PisosHotel.numHab="127";
           PisosHotel.NumHab.setText("127");
        }           // TODO add your handling code here:
    }//GEN-LAST:event_jButtonHab127ActionPerformed

    private void jButtonHab128ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHab128ActionPerformed
if("Ocupado".equals(jButtonHab128.getText())){
           JOptionPane.showMessageDialog(null,"habitacion no disponible");
        }else{
           jButtonHab128.setBackground(Color.BLACK);
           jButtonHab128.setForeground(Color.white);
           jButtonHab128.setText("Ocupado");  
           PisosHotel.numHab="128";
           PisosHotel.NumHab.setText("128");
        }           // TODO add your handling code here:
    }//GEN-LAST:event_jButtonHab128ActionPerformed

    private void jButtonHab129ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHab129ActionPerformed
if("Ocupado".equals(jButtonHab129.getText())){
           JOptionPane.showMessageDialog(null,"habitacion no disponible");
        }else{
           jButtonHab129.setBackground(Color.BLACK);
           jButtonHab129.setForeground(Color.white);
           jButtonHab129.setText("Ocupado");  
           PisosHotel.numHab="129";
           PisosHotel.NumHab.setText("129");
        }           // TODO add your handling code here:
    }//GEN-LAST:event_jButtonHab129ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PisosHotel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PisosHotel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PisosHotel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PisosHotel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PisosHotel().setVisible(true); 
                
            }
   
        });
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTextField NumHab;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton37;
    private javax.swing.JButton jButton38;
    private javax.swing.JButton jButton39;
    private javax.swing.JButton jButtonContinuar;
    private javax.swing.JButton jButtonHab100;
    private javax.swing.JButton jButtonHab101;
    private javax.swing.JButton jButtonHab102;
    private javax.swing.JButton jButtonHab103;
    private javax.swing.JButton jButtonHab104;
    private javax.swing.JButton jButtonHab105;
    private javax.swing.JButton jButtonHab106;
    private javax.swing.JButton jButtonHab107;
    private javax.swing.JButton jButtonHab108;
    private javax.swing.JButton jButtonHab109;
    private javax.swing.JButton jButtonHab110;
    private javax.swing.JButton jButtonHab111;
    private javax.swing.JButton jButtonHab112;
    private javax.swing.JButton jButtonHab113;
    private javax.swing.JButton jButtonHab114;
    private javax.swing.JButton jButtonHab115;
    private javax.swing.JButton jButtonHab116;
    private javax.swing.JButton jButtonHab117;
    private javax.swing.JButton jButtonHab118;
    private javax.swing.JButton jButtonHab119;
    private javax.swing.JButton jButtonHab120;
    private javax.swing.JButton jButtonHab121;
    private javax.swing.JButton jButtonHab122;
    private javax.swing.JButton jButtonHab123;
    private javax.swing.JButton jButtonHab124;
    private javax.swing.JButton jButtonHab125;
    private javax.swing.JButton jButtonHab126;
    private javax.swing.JButton jButtonHab127;
    private javax.swing.JButton jButtonHab128;
    private javax.swing.JButton jButtonHab129;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanelPiso2;
    private javax.swing.JPanel jPanelPisoUno;
    // End of variables declaration//GEN-END:variables
}
