/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package misClases;

import java.awt.Color;
import misClases.Hotel;
/**
 *
 * @author Alondra paulina v
 */
public class PisosHotel extends javax.swing.JFrame {

    /**
     * Creates new form PisosHotel
     */
    public PisosHotel() {
        initComponents();
         EstaOcupada();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelPisoUno = new javax.swing.JPanel();
        jButtonHab102 = new javax.swing.JButton();
        jButtonHab101 = new javax.swing.JButton();
        jButtonHab100 = new javax.swing.JButton();
        jButtonHab105 = new javax.swing.JButton();
        jButtonHab104 = new javax.swing.JButton();
        jButtonHab103 = new javax.swing.JButton();
        jButtonHab108 = new javax.swing.JButton();
        jButtonHab107 = new javax.swing.JButton();
        jButtonHab106 = new javax.swing.JButton();
        jButtonHab111 = new javax.swing.JButton();
        jButtonHab110 = new javax.swing.JButton();
        jButtonHab109 = new javax.swing.JButton();
        jButtonHab114 = new javax.swing.JButton();
        jButtonHab113 = new javax.swing.JButton();
        jButtonHab112 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jPanelPiso2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButtonHab115 = new javax.swing.JButton();
        jButtonHab116 = new javax.swing.JButton();
        jButtonHab117 = new javax.swing.JButton();
        jButtonHab118 = new javax.swing.JButton();
        jButtonHab119 = new javax.swing.JButton();
        jButtonHab120 = new javax.swing.JButton();
        jButtonHab121 = new javax.swing.JButton();
        jButtonHab122 = new javax.swing.JButton();
        jButtonHab123 = new javax.swing.JButton();
        jButtonHab124 = new javax.swing.JButton();
        jButtonHab125 = new javax.swing.JButton();
        jButtonHab126 = new javax.swing.JButton();
        jButtonHab127 = new javax.swing.JButton();
        jButtonHab128 = new javax.swing.JButton();
        jButtonHab129 = new javax.swing.JButton();
        jButton37 = new javax.swing.JButton();
        jButton38 = new javax.swing.JButton();
        jButton39 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelPisoUno.setBackground(new java.awt.Color(255, 255, 255));

        jButtonHab102.setBackground(new java.awt.Color(213, 131, 44));
        jButtonHab102.setText("102");

        jButtonHab101.setBackground(new java.awt.Color(213, 131, 44));
        jButtonHab101.setText("101");

        jButtonHab100.setBackground(new java.awt.Color(213, 131, 44));
        jButtonHab100.setText("100");
        jButtonHab100.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHab100ActionPerformed(evt);
            }
        });

        jButtonHab105.setBackground(new java.awt.Color(245, 230, 104));
        jButtonHab105.setText("105");

        jButtonHab104.setBackground(new java.awt.Color(213, 131, 44));
        jButtonHab104.setText("104");

        jButtonHab103.setBackground(new java.awt.Color(213, 131, 44));
        jButtonHab103.setText("103");

        jButtonHab108.setBackground(new java.awt.Color(245, 230, 104));
        jButtonHab108.setText("108");

        jButtonHab107.setBackground(new java.awt.Color(245, 230, 104));
        jButtonHab107.setText("107");

        jButtonHab106.setBackground(new java.awt.Color(245, 230, 104));
        jButtonHab106.setText("106");

        jButtonHab111.setBackground(new java.awt.Color(243, 181, 108));
        jButtonHab111.setText("111");

        jButtonHab110.setBackground(new java.awt.Color(243, 181, 108));
        jButtonHab110.setText("110");

        jButtonHab109.setBackground(new java.awt.Color(245, 230, 104));
        jButtonHab109.setText("109");

        jButtonHab114.setBackground(new java.awt.Color(213, 131, 44));
        jButtonHab114.setText("114");

        jButtonHab113.setBackground(new java.awt.Color(213, 131, 44));
        jButtonHab113.setText("113");

        jButtonHab112.setBackground(new java.awt.Color(243, 181, 108));
        jButtonHab112.setText("112");

        jButton16.setText("Alberca con vista al mar");

        jButton17.setText("Bar/Comedor");

        jButton18.setText("Cancha tennis");

        jButton19.setBackground(new java.awt.Color(213, 131, 44));
        jButton19.setText("Habitacion Sencilla");

        jButton20.setBackground(new java.awt.Color(245, 230, 104));
        jButton20.setText("Habitacion Doble");

        jButton21.setBackground(new java.awt.Color(243, 181, 108));
        jButton21.setText("Habitacion Triple");

        javax.swing.GroupLayout jPanelPisoUnoLayout = new javax.swing.GroupLayout(jPanelPisoUno);
        jPanelPisoUno.setLayout(jPanelPisoUnoLayout);
        jPanelPisoUnoLayout.setHorizontalGroup(
            jPanelPisoUnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPisoUnoLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanelPisoUnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanelPisoUnoLayout.createSequentialGroup()
                        .addGroup(jPanelPisoUnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelPisoUnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jButton16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanelPisoUnoLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jButton19)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                        .addGroup(jPanelPisoUnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanelPisoUnoLayout.createSequentialGroup()
                                .addComponent(jButton20, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton21, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(9, 9, 9))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPisoUnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanelPisoUnoLayout.createSequentialGroup()
                                    .addComponent(jButtonHab106, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jButtonHab107, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jButtonHab108, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanelPisoUnoLayout.createSequentialGroup()
                                    .addComponent(jButtonHab103, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jButtonHab104, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jButtonHab105, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelPisoUnoLayout.createSequentialGroup()
                                    .addComponent(jButtonHab109, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jButtonHab110, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jButtonHab111, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanelPisoUnoLayout.createSequentialGroup()
                                    .addComponent(jButtonHab100, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jButtonHab101, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jButtonHab102, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPisoUnoLayout.createSequentialGroup()
                                .addComponent(jButtonHab112, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonHab113, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButtonHab114, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(36, 36, 36))))
        );
        jPanelPisoUnoLayout.setVerticalGroup(
            jPanelPisoUnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPisoUnoLayout.createSequentialGroup()
                .addGroup(jPanelPisoUnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelPisoUnoLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanelPisoUnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton19)
                            .addComponent(jButton21)
                            .addComponent(jButton20))
                        .addGap(58, 58, 58)
                        .addGroup(jPanelPisoUnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonHab102, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonHab101, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonHab100, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelPisoUnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonHab105, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonHab104, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonHab103, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                        .addGroup(jPanelPisoUnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonHab108, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
                            .addComponent(jButtonHab106, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
                            .addComponent(jButtonHab107, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)))
                    .addGroup(jPanelPisoUnoLayout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(jButton16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(jPanelPisoUnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelPisoUnoLayout.createSequentialGroup()
                        .addGroup(jPanelPisoUnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonHab109, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonHab110, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonHab111, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelPisoUnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonHab114, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonHab113, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonHab112, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jButton17, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton18, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        jPanelPiso2.setBackground(new java.awt.Color(255, 255, 255));
        jPanelPiso2.setPreferredSize(new java.awt.Dimension(578, 569));

        jLabel2.setText("Piso 2");

        jButtonHab115.setBackground(new java.awt.Color(245, 230, 104));
        jButtonHab115.setText("115");

        jButtonHab116.setBackground(new java.awt.Color(245, 230, 104));
        jButtonHab116.setText("116");

        jButtonHab117.setBackground(new java.awt.Color(245, 230, 104));
        jButtonHab117.setText("117");

        jButtonHab118.setBackground(new java.awt.Color(245, 230, 104));
        jButtonHab118.setText("118");

        jButtonHab119.setBackground(new java.awt.Color(245, 230, 104));
        jButtonHab119.setText("119");

        jButtonHab120.setBackground(new java.awt.Color(245, 230, 104));
        jButtonHab120.setText("120");

        jButtonHab121.setBackground(new java.awt.Color(243, 181, 108));
        jButtonHab121.setText("121");
        jButtonHab121.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHab121ActionPerformed(evt);
            }
        });

        jButtonHab122.setBackground(new java.awt.Color(243, 181, 108));
        jButtonHab122.setText("122");

        jButtonHab123.setBackground(new java.awt.Color(243, 181, 108));
        jButtonHab123.setText("123");

        jButtonHab124.setBackground(new java.awt.Color(243, 181, 108));
        jButtonHab124.setText("124");

        jButtonHab125.setBackground(new java.awt.Color(243, 181, 108));
        jButtonHab125.setText("125");

        jButtonHab126.setBackground(new java.awt.Color(243, 181, 108));
        jButtonHab126.setText("126");

        jButtonHab127.setBackground(new java.awt.Color(245, 230, 104));
        jButtonHab127.setText("127");

        jButtonHab128.setBackground(new java.awt.Color(213, 131, 44));
        jButtonHab128.setText("128");

        jButtonHab129.setBackground(new java.awt.Color(213, 131, 44));
        jButtonHab129.setText("129");

        jButton37.setText("Guarderia");

        jButton38.setText("Spa");

        jButton39.setText("Area de video Juegos");

        jButton1.setBackground(new java.awt.Color(51, 51, 51));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Continuar");

        javax.swing.GroupLayout jPanelPiso2Layout = new javax.swing.GroupLayout(jPanelPiso2);
        jPanelPiso2.setLayout(jPanelPiso2Layout);
        jPanelPiso2Layout.setHorizontalGroup(
            jPanelPiso2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPiso2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanelPiso2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelPiso2Layout.createSequentialGroup()
                        .addGroup(jPanelPiso2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelPiso2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jButtonHab118, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButtonHab121, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButtonHab115, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelPiso2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelPiso2Layout.createSequentialGroup()
                                .addGroup(jPanelPiso2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButtonHab119, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButtonHab122, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButtonHab116, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanelPiso2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanelPiso2Layout.createSequentialGroup()
                                        .addGroup(jPanelPiso2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jButtonHab117, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jButtonHab123, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jButtonHab120, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(jPanelPiso2Layout.createSequentialGroup()
                                        .addGap(122, 122, 122)
                                        .addComponent(jButton39, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE))))
                            .addComponent(jButton37, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanelPiso2Layout.createSequentialGroup()
                        .addGroup(jPanelPiso2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelPiso2Layout.createSequentialGroup()
                                .addComponent(jButtonHab127, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonHab128, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonHab129, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelPiso2Layout.createSequentialGroup()
                                .addComponent(jButtonHab124, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonHab125, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonHab126, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(27, 27, 27)
                        .addComponent(jButton38, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanelPiso2Layout.createSequentialGroup()
                .addGap(243, 243, 243)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelPiso2Layout.setVerticalGroup(
            jPanelPiso2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPiso2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanelPiso2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelPiso2Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jButton37, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanelPiso2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonHab115, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonHab116, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonHab117, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanelPiso2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanelPiso2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanelPiso2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonHab118, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonHab119, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonHab120, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelPiso2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonHab121, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonHab122, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonHab123, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanelPiso2Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jButton39, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(jPanelPiso2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelPiso2Layout.createSequentialGroup()
                        .addGroup(jPanelPiso2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonHab124, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonHab125, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonHab126, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelPiso2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonHab127, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonHab128, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonHab129, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jButton38, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelPisoUno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                .addComponent(jPanelPiso2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelPisoUno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanelPiso2, javax.swing.GroupLayout.DEFAULT_SIZE, 575, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonHab121ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHab121ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonHab121ActionPerformed
    public void EstaOcupada(){
        Habitacion[] aux;
        aux = new Habitacion[30];
       // aux= new Habitacion[30];

        int op=0 ;
          jButtonHab100.setBackground(Color.BLACK);
          jButtonHab100.setText("ocupado");
          for(int i=0;.size>=i;i++){
          }
        switch(op){
            case 1:
                jButtonHab100.setBackground(Color.BLACK);
                jButtonHab100.setText("Ocupado"); 
                
                break;
            case 2:
                
                break;
            case 3:
                
                break;
            case 4:
                
                break;
             
                
        }
    }
    
    private void jButtonHab100ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHab100ActionPerformed
       // TODO add your handling code here:
           jButtonHab100.setBackground(Color.BLACK);
           jButtonHab100.setText("Ocupado");   
    }//GEN-LAST:event_jButtonHab100ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PisosHotel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PisosHotel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PisosHotel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PisosHotel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PisosHotel().setVisible(true); 
                
            }
   
        });
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton37;
    private javax.swing.JButton jButton38;
    private javax.swing.JButton jButton39;
    private javax.swing.JButton jButtonHab100;
    private javax.swing.JButton jButtonHab101;
    private javax.swing.JButton jButtonHab102;
    private javax.swing.JButton jButtonHab103;
    private javax.swing.JButton jButtonHab104;
    private javax.swing.JButton jButtonHab105;
    private javax.swing.JButton jButtonHab106;
    private javax.swing.JButton jButtonHab107;
    private javax.swing.JButton jButtonHab108;
    private javax.swing.JButton jButtonHab109;
    private javax.swing.JButton jButtonHab110;
    private javax.swing.JButton jButtonHab111;
    private javax.swing.JButton jButtonHab112;
    private javax.swing.JButton jButtonHab113;
    private javax.swing.JButton jButtonHab114;
    private javax.swing.JButton jButtonHab115;
    private javax.swing.JButton jButtonHab116;
    private javax.swing.JButton jButtonHab117;
    private javax.swing.JButton jButtonHab118;
    private javax.swing.JButton jButtonHab119;
    private javax.swing.JButton jButtonHab120;
    private javax.swing.JButton jButtonHab121;
    private javax.swing.JButton jButtonHab122;
    private javax.swing.JButton jButtonHab123;
    private javax.swing.JButton jButtonHab124;
    private javax.swing.JButton jButtonHab125;
    private javax.swing.JButton jButtonHab126;
    private javax.swing.JButton jButtonHab127;
    private javax.swing.JButton jButtonHab128;
    private javax.swing.JButton jButtonHab129;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanelPiso2;
    private javax.swing.JPanel jPanelPisoUno;
    // End of variables declaration//GEN-END:variables
}
